# Site settings
name: irfan
title: irfan
description: The ultimate website where you can download official ROMs and firmware packages for Xiaomi devices!
keywords: xiaomi, xiaomi firmware, xiaomi firmware updater, firmware updater, firmware download, firmware, firmware downloader, firmware update, xiaomi firmware download, xiaomi firmware update, Xiaomi update, XDA, Xiaomi XDA, Firmware XDA, yshalsager, xfu, redmi, mi, pocophone, poco
url: https://xiaomifirmware.com
permalink: /:categories/:title/
repository: irfaaan/irfaaan.github.io
author: yshalsager
email: contact@xiaomifirmwareupdater.com

plugins:
  - jekyll-feed
  - jekyll-sitemap

members:
  - berkantkz
  - yshalsager
  - irfaaan

exclude:
  - data_generator/
